/* AUTO-GENERATED by experiments/nrf24_link_monitor_train.py
 * Generated   : 2026-04-19 01:39
 * Test accuracy: 100.0%
 * Samples      : 1200
 * Tree depth   : 2
 * Tree nodes   : 5
 *
 * Features:
 *   pkt_rate    — packets per second
 *   loss_rate   — fraction missed, 0.0–1.0
 *   avg_iat_ms  — mean inter-arrival time (ms)
 *   burst_score — IAT coeff. of variation, 0–3
 *
 * Classes: 0=NORMAL  1=WEAK  2=INTERFERENCE
 */
#pragma once
#include <stdint.h>

#define LINK_NORMAL       0
#define LINK_WEAK         1
#define LINK_INTERFERENCE 2

static const char * const LINK_STATE_STR[] = {"NORMAL", "WEAK", "INTERF"};

static inline int model_predict(float pkt_rate, float loss_rate,
                                 float avg_iat_ms, float burst_score)
{
    if (burst_score <= 1.0749f) {
        if (pkt_rate <= 6.4981f) {
            return 1; /* WEAK */
        } else {
            return 0; /* NORMAL */
        }
    } else {
        return 2; /* INTERFERENCE */
    }
}
